apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: prometheus-pod-rs
spec: 
  replicas: 3
  selector:
    matchExpressions:
      - { key: env, operator: In, values: [Developer] }
  template:
    metadata:
      name: prometheus-pod-rs
      labels:
        env: Developer
        region: In
    spec:
      containers:
      - name: prometheus-con
        image: vimal13/prometheus