apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: grafana-pod-rs
spec: 
  replicas: 3
  selector:
    matchExpressions:
      - { key: env, operator: In, values: [Developer] }
  template:
    metadata:
      name: grafana-pod-rs
      labels:
        env: Developer
        region: In
    spec:
      containers:
      - name: grafana-con
        image: vimal13/grafana
        ports:
          - containerPort: 3000
            name: grafana
        volumeMounts:
              - name: grafana-pvc
                mountPath: /root/kube_code/prom_graf
      volumes:
        - name: grafana-pvc
          persistentVolumeClaim:
              claimName: grafana-pvc 
 